### ISSUE TITLE
UG: Change name of parameter for adding a task

### ISSUE THREAD

**Issue by JeremyInElysium** [CS2113-AY1819S1-W13-3/main#27]
Adds a task to the task book +
Format: `add t/ACTION d/DAY [w/WEEK] [m/MONTH]...`

Possible to change "ACTION" to "TASK_TITLE" for a more accurate depiction?
Adding a milestone also utilizes the t/ prefix but "ACTION" wouldn't be appropriate in the context of milestone

**Comment by chelseyong** [comment]
Okay noted!
