### ISSUE TITLE
Inconsistent Deadline format

### ISSUE THREAD

**Issue by chelseyong** [CS2113-AY1819S1-W13-3/main#58]
@ChanChunCheong DeferDeadline has an improper deadline format. 
You may consider switching to dd/_day_ mm/_month_ yyyy/_year_ or _day_/_month_/_year_, instead of de/_DEADLINE_
@emobeany will you be implementing deadline w/o prefixes?

Do tests for the feature as well. Look into the index format for deferDeadline.

**Comment by ChanChunCheong** [comment]
Solved issue
